#!/usr/bin/env bash
# Comment
prints () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " 'NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}
if [ $# -eq 1 ];
then
    Domain_information "$1" "www"
    Domain_information "$1" "lb-01"
    Domain_information "$1" "web-01"
    Domain_information "$1" "web-02"
elif [ $# -eq 2 ];
then
     prints "$2.$1" "$2"
fi

