#!/usr/bin/env bash
# Write a Bash script that pings an IP address
#* Accepts a string as an argument
#* Displays Usage: 5-is_the_host_on_the_network
#* Ping the IP 5 times

if [ "s#" -eq 0 ]; then
       echo "usage: 5-ig-the_host_on_the_network{IP_ADDRESS}"
else
 ping -e 5 "$1"
fi 
