#!/usr/bin/env bash
# This script configures Nginx to listen on port 80.
#remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
configure Nginx to listen to port 80 for all active IPv4 IPs
in -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart Nginx
service nginx restart
